live_config_reload = true

# theme
import = [
  "~/.config/alacritty/themes/theme.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[[keyboard.bindings]]
#chars = "\u0002%\u0002\u001B2"
#chars = "\x02\x22\x02\x1b2"
chars = "\u0002\u0022"
key = "N"
mods = "Command"

[[keyboard.bindings]]
#chars = "\u0002%\u0002\u001B1"
#chars = "\x02\x25\x02\x1b1"
chars = "\u0002%"
key = "N"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u00020"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002o"
key = "O"
mods = "Command"

[[keyboard.bindings]]
#chars = "\u0002x\u0002\u001B1\u0002\u001B2"
#chars = "\x02\x78\x02\x1b1\x02\x1b2"
chars = "\u0002x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002z"
key = "Z"
mods = "Command"

#[[hints.enabled]]
#command = "open"
#hyperlinks = true
#post_processing = true
#persist = false
#mouse.enabled = true

[scrolling]
history = 10000

[window]
decorations = "buttonless"
dynamic_padding = false

[window.padding]
x = 8
y = 8
